In [ ]:
# Numpy:-
--->Numpy is the fundamental pacakge for scientific computing in python.
--->It helps us to create multidimensional array.
--->There are 3types of arrays 1D, 2D, 3D.


In [1]:
import numpy as np

In [3]:
!pip install numpy

In [31]:
#creation of 1D array:
ar_1=np.array([10,20,30,40])
print(ar_1)

[10 20 30 40]


In [35]:
ar_1.shape

(4,)

In [15]:
ar_1.dtype

dtype('int32')

In [16]:
type(ar_1)

numpy.ndarray

In [23]:
ar_2=np.array({10,20,40,40})
print(ar_2)

{40, 10, 20}


In [24]:
type(ar_2)

numpy.ndarray

In [36]:
ar_2.shape

()

In [25]:
ar_1.ndim

0

In [28]:
#2D array.

two_arr=np.array([[10,204,33],[30,40,98],[90,89,44]])
print(two_arr)

[[ 10 204  33]
 [ 30  40  98]
 [ 90  89  44]]


In [29]:
two_arr.ndim

2

In [37]:
two_arr.shape

(3, 3)

# What is the differene between numpy array and python list?

In [38]:
ar_1

array([10, 20, 30, 40])

In [39]:
print(ar_1)

[10 20 30 40]


In [40]:
list_1=[10,20,30,40]
list_1

[10, 20, 30, 40]

In [45]:
list_1=[10,20,30,40]
list_2=[30,40,80,90]

list_out=[]

for i,j in zip(list_1,list_2):
    list_out.append(i+j)
print(list_out)



[40, 60, 110, 130]


In [54]:
ar_3=np.array([30,40,50,60,"str"])
print(ar_3)
type(ar_3)
ar_3.dtype

['30' '40' '50' '60' 'str']


dtype('<U11')

In [51]:
ar_1+ar_3 # we can use +,-,*,%etc...

array([ 40,  60,  80, 100])

In [52]:
list_1+list_2

[10, 20, 30, 40, 30, 40, 80, 90]

# Indexing and Slicing:

In [55]:
ar_1

array([10, 20, 30, 40])

In [60]:
ar_1[2]  #indexing

30

In [61]:
ar_1[3]

40

In [62]:
ar_1[-2]

30

In [64]:
print(two_arr)

[[ 10 204  33]
 [ 30  40  98]
 [ 90  89  44]]


In [66]:
x=two_arr[0][0]
x.ndim

0

In [72]:
two_arr[0,:]

array([ 10, 204,  33])

In [73]:
two_arr[0:1,:]

array([[ 10, 204,  33]])

# Creation of different types of arrays:

In [4]:
ar_num=np.array([1,2,3,4,5],dtype="float")
print(ar_num)

[1. 2. 3. 4. 5.]


In [5]:
ar_com=np.array([1,2,3,4,5],dtype="complex")
print(ar_com)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [13]:
#Creating array with the help of arrange method.
#1D array

x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
m=np.arange(2,21,2)
print(m)

[ 2  4  6  8 10 12 14 16 18 20]


In [18]:
#2D array 
#with reshape

np.arange(31,52,3).reshape(7,1)

array([[31],
       [34],
       [37],
       [40],
       [43],
       [46],
       [49]])

In [22]:
np.arange(1,7).reshape(3,-1) # 2*3,3*2,6*1,1*6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
np.arange(1,7).reshape(-1,6)

array([[1, 2, 3, 4, 5, 6]])

In [27]:
#array of zeros
np.zeros((10),dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.zeros((10,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
#array of ones
np.ones((10,10),dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [39]:
#array of random elements
np.random.random(10)

array([0.29792282, 0.63558562, 0.15566847, 0.892412  , 0.17730721,
       0.93593029, 0.82259156, 0.32409296, 0.59428228, 0.04913548])

In [43]:
np.random.seed(3)



In [45]:
np.random.random((10,5))

array([[0.20541034, 0.20137871, 0.51403506, 0.08722937, 0.48358553],
       [0.36217621, 0.70768662, 0.74674622, 0.69109292, 0.68918041],
       [0.37360012, 0.6681348 , 0.33984866, 0.57279387, 0.32580716],
       [0.44514505, 0.06152893, 0.24267542, 0.97160261, 0.2305842 ],
       [0.69147751, 0.65047686, 0.72393914, 0.47508861, 0.59666377],
       [0.06696942, 0.07256214, 0.19897603, 0.151861  , 0.10010434],
       [0.12929386, 0.55327773, 0.18781482, 0.95210124, 0.68161178],
       [0.54101967, 0.7071806 , 0.26388667, 0.92672568, 0.83919306],
       [0.7263195 , 0.48023996, 0.84210319, 0.74475232, 0.66032591],
       [0.91397527, 0.63366556, 0.36594058, 0.55284457, 0.19638058]])

In [53]:
np.random.randint(5,100,(5,10))

array([[16, 40, 90, 97, 54, 77, 94, 39, 16, 94],
       [94, 64,  9, 90, 98,  5, 61, 99, 50, 76],
       [26, 39, 34, 47, 12, 99, 35, 81, 80, 44],
       [62, 54, 49, 26, 99, 46, 76, 97, 39, 20],
       [27, 50, 41, 45, 95, 57, 14, 24, 74, 59]])

# Array attributes:

In [26]:
a1=np.arange(10)
a2=np.arange(12,dtype="float").reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [27]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a1.size

10

In [31]:
a2.shape

(3, 4)

In [32]:
a3.shape

(2, 2, 2)

In [38]:
#changing the datatype of pre-existing array

a2=a2.astype(np.int32)
print(a2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [34]:
a2=a2+3
a2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [35]:
a2>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
a4=np.arange(12,24).reshape(3,4)
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
a2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [40]:
print(a4+a2)

[[15 17 19 21]
 [23 25 27 29]
 [31 33 35 37]]


In [41]:
print(a4-a2)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


# Array functions:

In [43]:
from numpy.core.fromnumeric import prod

print(np.prod(a2))

639472640


In [44]:
np.prod(a4)

816826368

In [45]:
a2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [46]:
np.min(a2)

3

In [47]:
np.max(a2)

14

In [48]:
np.sum(a2)

102

In [49]:
print(np.mean(a2))

8.5


In [51]:
#finding mean across the rows
np.mean(a2,axis=1)   #rows=1, columns=0

array([ 4.5,  8.5, 12.5])

In [52]:
np.mean(a2,axis=0)

array([ 7.,  8.,  9., 10.])

In [54]:
np.std(a2)  #standrd devation

3.452052529534663

In [ ]:
A measure of how much variation exists from the mean of a data 

In [56]:
np.var(a2)  #variance 

11.916666666666666

In [57]:
#dot product of two array

a2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [58]:
a4 

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
mat=np.arange(12,24).reshape(4,3)

In [64]:
mat

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [65]:
np.dot(a2,mat)

array([[312, 330, 348],
       [576, 610, 644],
       [840, 890, 940]])

In [66]:
#how to iterate over matrix:

mat

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [67]:
for i in mat:
    print(i)

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


In [68]:
for i in mat:
    for j in i:
        print(j)

12
13
14
15
16
17
18
19
20
21
22
23


In [69]:
for i in np.nditer(mat):
    print(i)

12
13
14
15
16
17
18
19
20
21
22
23


In [70]:
#conversion of 2D into 1D


mat.ravel()



array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
#stacking and spliting.